mindmap
  root((Mapa mental - didac_MatEsp))
    matemáticas / matemática / educación 27
      matemáticas
      matemática
      educación
      enseñanza
      secundaria
      puede
    currículo / estudio / indagación 12
      currículo
      estudio
      indagación
      educación
      puede
      matemática
    matemáticas / matemática / miembros 10
      matemáticas
      matemática
      miembros
      problema
      futuros
      gente
    materias / ahora / característica 1
      materias
      ahora
      característica
      dominante
      técnicas
      profano
    chevallard / yves / free 1
      chevallard
      yves
      free
      mañana
      inmenso
      gracias